// ATEDataTypeLib.idl : IDL source for ATEDataTypeLib
//

// This file will be processed by the MIDL tool to
// produce the type library (ATEDataTypeLib.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

typedef [helpstring("ATE Base Data Types")]
enum {
	[helpstring("Unit")]dsUnit = 1,
	[helpstring("Digit")]dsData = 2,
	[helpstring("Spec Name")]dsSpec = 3,
	[helpstring("Operator")]dsOper = 4,
	[helpstring("String")]dsStr = 5
} dsBaseDataType;

typedef [helpstring("Operator Types")]
enum {
	[helpstring("Plus")]dsPlus = 1,
	[helpstring("Substract")]dsSub = 2,
	[helpstring("Multiply")]dsMul = 3,
	[helpstring("Divide")]dsDiv = 4,
	[helpstring("Power")]dsPow = 5
} dsOperatorType;

[
	object,
	uuid(F5A367FA-9E81-4359-904C-9F0F4CB0E156),
	dual,
	pointer_default(unique)
]
interface IATEBaseData : IDispatch {
	[propget, id(1)] HRESULT StrValue([out, retval] BSTR* pVal);
	[propput, id(1)] HRESULT StrValue([in] BSTR newVal);
	[propget, id(2)] HRESULT Value([out, retval] DOUBLE* pVal);
	[propget, id(3)] HRESULT SubLeft([out, retval] IATEBaseData** pVal);
	[propget, id(4)] HRESULT SubRight([out, retval] IATEBaseData** pVal);
	[id(5)] HRESULT SetSubLeft([in] dsBaseDataType DataType, [out, retval] IATEBaseData** pSubLeft);
	[id(6)] HRESULT SetSubRight([in] dsBaseDataType DataType, [out, retval] IATEBaseData** pSubRight);
};
interface IRemarks;
[
	object,
	uuid(2BB8234E-CC76-4D78-BD8A-68584DD5B319),
	dual,
	pointer_default(unique)
]
interface IRemark : IDispatch {
	[propget, id(1)] HRESULT Value([out, retval] BSTR* pVal);
	[propput, id(1)] HRESULT Value([in] BSTR newVal);
	[propget, id(2)] HRESULT SubRemarks([out, retval] IRemarks** pVal);
	[propput, id(2)] HRESULT SubRemarks([in] IRemarks* newVal);
};
[
	object,
	uuid(FDEE2A0C-3519-4A93-B005-DE011BB39984),
	dual,
	pointer_default(unique)
]
interface IRemarks : IDispatch {
	[id(1)] HRESULT AddRemark([out, retval] IRemark ** ppRemark);
	[propget, id(2)] HRESULT Count([out, retval] LONG* pnCount);
	[propget, id(DISPID_VALUE)] HRESULT Item([out, retval] IRemark ** ppRemark);
	[propget, id(DISPID_NEWENUM)] HRESULT _NewEnum([out, retval] IUnknown** ppEnum);
};
[
	object,
	uuid(43D61594-6ED1-4CBA-9FA2-96737EA29629),
	dual,
	pointer_default(unique)
]
interface IATEColumn : IDispatch {
};
[
	object,
	uuid(38D1DC1A-C92A-4D04-AEDF-FFC5C1CA6E09),
	dual,
	pointer_default(unique)
]
interface IATEColumns : IDispatch {
};
[
	object,
	uuid(22792973-9F35-4089-8491-CAD658732BE9),
	dual,
	pointer_default(unique)
]
interface IATETable : IDispatch {
	[id(1)] HRESULT debug1([out, retval] BSTR* val);
};
[
	object,
	uuid(720ED246-1832-4FDC-BD27-72E9EC13C209),
	dual,
	pointer_default(unique)
]
interface IATETables : IDispatch {
};
[
	uuid(753D2A23-C6D8-407D-84F8-5E17C90F6E6D),
	version(1.0),
]
library ATEDataTypeLib
{
	importlib("stdole2.tlb");	
	[
		uuid(FFA66125-F3AF-4FC6-85A1-CA3267069803)
	]
	coclass ATETable
	{
		[default] interface IATETable;
	}; 
	[
		uuid(3108B14F-43F2-4B8D-A11E-92621F5CD6BB)
	]
	coclass Unit
	{
		[default] interface IATEBaseData;
	};
	[
		uuid(5B222910-BEAA-4F8F-B0E9-C7C7F7E1DE22)
	]
	coclass Digit
	{
		[default] interface IATEBaseData;
	};
	[
		uuid(E70C13FD-A527-4C25-84E9-541D121747F6)
	]
	coclass Operator
	{
		[default] interface IATEBaseData;
	};
	[
		uuid(B2826957-0EAA-4504-9887-81B129E6474D)
	]
	coclass String
	{
		[default] interface IATEBaseData;
	};
};

